### ISSUE TITLE
Script doesnt work

### ISSUE THREAD

**Issue by bueroblanko** [kitzler-walli/Screenshot-to-Nextcloud#2]
Unfortunatelly i dont get the script to run. When i open it in Automator and test it manually i do get the follwoing yellow-warning in Step1: "The action "Filter Finder Items" was not supplied with the required data." and then the second red-warning in Step2: 
"No item references were passed to the Move Finder Items action." 

Seems like the file cannot be found even when its called "Screenshot 2023-01-16 at 17.40.49.png". What am i doing wrong?

**Comment by kitzler-walli** [comment]
The workflow has to be attached to a folder - in my case I used the desktop.
Does it look like this on your mac?
![image](https://user-images.githubusercontent.com/1926992/212747204-2cf7f90f-79d8-432c-9412-809367df7fb5.png)

**Comment by bueroblanko** [comment]
![b32c6838aaba4e75a28341154de31f6e](https://user-images.githubusercontent.com/49558119/212756498-6b237ea5-fb84-40eb-b2f5-550d7307e88c.jpg)
yes! it looks the same. I only need to change: URL/user/apppassword in the script-code, right?

**Comment by kitzler-walli** [comment]
You need to select a folder for Move Finder Items - it seems like the folder does not exist - could that be the reason?
This folder has to be a synced folder within Nextcloud.

**Comment by bueroblanko** [comment]
It does exist and is also synched with my Nextcloud, I also tried a different one as a test, still no result. When i install the workflow file i get asked the following dialog. Here is also "Desktop" the correct location, right?
![image](https://user-images.githubusercontent.com/49558119/212890498-dddf54f7-2afa-40c8-b3e1-a5829833ac0a.png)

**Comment by kitzler-walli** [comment]
Sorry I can't find anything wrong - when you first run Automator you have to give it access to the Desktop - could it be that you denied that request?

**Comment by bueroblanko** [comment]
![image](https://user-images.githubusercontent.com/49558119/212914137-76afcc51-cbd2-472f-b2cf-65e75829191d.png)

Nah access is granted. I also tried a different folder as desktop. 
Nevertheless, thanks for providing the code and help me with troubleshooting!

**Comment by kitzler-walli** [comment]
Thats the installer - not Automator itself. But I just checked - in my case Automator isn't even listed for the apps accessing the desktop folder and it still works - really strange. Sorry that I can't be of any further assistance.

**Comment by bueroblanko** [comment]
Nevertheless, thanks for your help :)
